import Foundation

/// Produces `FixedMathTables.swift`, the only place platform floating-point math feeds the simulation.
///
/// It runs at development time; the output is committed and the simulation reads the integer literals. A test
/// regenerates the file and compares it with the committed copy, so hand edits and generator drift both fail.
public enum TableGenerator {
    public static let quarterTurnResolution = 1024
    public static let fractionScale = 65_536.0
    public static let angleUnitsPerTurn = 4096.0

    /// `round(sin(index / 1024 × π/2) × 65536)` for `index` in `0...1024`.
    public static func quarterSineTable() -> [Int32] {
        (0...quarterTurnResolution).map { index in
            let radians = Double(index) / Double(quarterTurnResolution) * (Double.pi / 2)
            return Int32((sin(radians) * fractionScale).rounded())
        }
    }

    /// `round(atan(index / 1024) / 2π × 4096)` for `index` in `0...1024`.
    public static func arctangentTable() -> [Int32] {
        (0...quarterTurnResolution).map { index in
            let ratio = Double(index) / Double(quarterTurnResolution)
            return Int32((atan(ratio) / (2 * Double.pi) * angleUnitsPerTurn).rounded())
        }
    }

    public static func swiftSource() -> String {
        var source = """
            // Generated by `fermansim gen-tables`. Do not edit; regenerate instead.

            extension FixedMath {
                /// `round(sin(index / 1024 × π/2) × 65536)` for `index` in `0...1024`.
                static let quarterSineTable: [Int32] = [

            """
        appendRows(of: quarterSineTable(), to: &source)
        source += """
                ]

                /// `round(atan(index / 1024) / 2π × 4096)` for `index` in `0...1024`.
                static let arctangentTable: [Int32] = [

            """
        appendRows(of: arctangentTable(), to: &source)
        source += """
                ]
            }

            """
        return source
    }

    private static func appendRows(of values: [Int32], to source: inout String) {
        let valuesPerRow = 12
        for rowStart in stride(from: 0, to: values.count, by: valuesPerRow) {
            let row = values[rowStart..<min(rowStart + valuesPerRow, values.count)]
            source += "        " + row.map { "\(groupedLiteral($0))," }.joined(separator: " ") + "\n"
        }
    }

    /// Matches swift-format's `GroupNumericLiterals` rule so the generated file passes lint unchanged.
    private static func groupedLiteral(_ value: Int32) -> String {
        let digits = String(value.magnitude)
        guard digits.count > 4 else {
            return String(value)
        }
        var grouped = ""
        for (offset, digit) in digits.enumerated() {
            if offset > 0 && (digits.count - offset) % 3 == 0 {
                grouped += "_"
            }
            grouped.append(digit)
        }
        return value < 0 ? "-" + grouped : grouped
    }
}
